### PR TITLE
Resolve breaking issues and update README

### PR DESCRIPTION
**Pull request by RickMohr**
* Package client-side assets using `webpack` instead of `grunt`
* Use updated URL for `go` distribution, and updated version 1.6.3
* Remove unnecessary library references
* Update README with instructions for configuring a Google Maps API key
* Make media folder world-writable so `celeryd` can write to it

Connects #41
Connects #42
Connects #43
Connects #45

### CODE REVIEW

**Comment by maurizi** [comment]
Attempting to provision from scratch failed with the following error:
```
==> default: Cannot add PPA: 'ppa:chris-lea/node.js'.
==> default: Please check that the PPA name or format is correct.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by maurizi** [comment]
Destroying and rebuilding again "magically" fixed the above the error, and provisioning finished successfully this time.

I'm getting the following error when I attempt to go to the homepage now:
```
WebpackError at /
            ModuleBuildError in 
            Module build failed: Error: Missing binding /usr/local/otm/app/node_modules/node-sass/vendor/linux-x64-14/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node 0.12.x

Found bindings for the following environments:
  - Linux 64-bit with Node 0.10.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
```

**Comment by andriyr** [comment]
@RickMohr I've tried your `update-2016` branch and it worked for me, thanks!

Is there anything I can help with to merge your fix into master branch of original repository?

**Comment by RickMohr** [comment]
Thanks for trying it out and letting me know! We'll merge it in early 2017 once it goes through a code review.

**Comment by maurizi** [comment]
:+1: Works great! Thanks @RickMohr!

**Pull request merged**
