### PR TITLE
Fix builds

### PR DESCRIPTION
**Pull request by maurizi**

### CODE REVIEW

**Comment by jwalgran** [comment]
We will be running Postgres 9.4 in production soon. Is there a reason for only going to up to 9.3 here?

**Comment by maurizi** [comment]
Because 9.3 is the latest package available in the Trusty repositories.  9.4 is only available in Utopic or later.

**Comment by jwalgran** [comment]
My first attempt at a fresh `vagrant up` failed

```
...
==> default: /tmp/vagrant-shell: 81: /tmp/vagrant-shell:
==> default: go: not found
==> default: # github.com/tools/godep
==> default: /home/vagrant/.gopath/src/github.com/tools/godep/list.go:163: undefined: build.MultiplePackageError
```

Running `vagrant provision` after that 

```
==> default: mkdir:
==> default: cannot create directory ‘/home/vagrant/.gopath’
==> default: : File exists
==> default: # github.com/tools/godep
==> default: /home/vagrant/.gopath/src/github.com/tools/godep/list.go:163: undefined: build.MultiplePackageError
```

**Comment by maurizi** [comment]
@jwalgran I fixed this issues with installing `go` (I needed to change from `/bin/sh` to `/bin/bash`).

The stuff with `godep` seems to have been a temporary fluke.

**Comment by jwalgran** [comment]
We need to update the README.md to remove references to sourcing the now deceased virtual env

**Comment by maurizi** [comment]
> We need to update the README.md to remove references to sourcing the now deceased virtual env.

@jwalgran That was already done?

**Comment by jwalgran** [comment]
Sorry, I was looking at the README on github on the wrong branch. I see in the diff that the line is removed.

**Comment by jwalgran** [comment]
I hit a strange collect static error

```
==> default: Running "shell:collect_static" (shell) task
==> default: Traceback (most recent call last):
==> default:   File "manage.py", line 8, in <module>
==> default:     from django.core.management import execute_from_command_line
==> default: ImportError: No module named django.core.management
```

Trying a fresh provision from a brand new checkout

**Comment by jwalgran** [comment]
I am seeing python package build failures like this in the provisioner output.
```
==> default:   Running setup.py bdist_wheel for django-storages
==> default:   Complete output from command /usr/local/otm/env/bin/python -c "import setuptools;__file__='/tmp/pip-build-hOv2f5/django-storages/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpqR9sQApip-wheel-:
==> default:   Traceback (most recent call last):
==> default:     File "<string>", line 1, in <module>
==> default:     File "/tmp/pip-build-hOv2f5/django-storages/setup.py", line 24, in <module>
==> default:       zip_safe = False,
==> default:     File "/usr/lib/python2.7/distutils/core.py", line 138, in setup
==> default:       ok = dist.parse_command_line()
==> default:     File "/usr/local/otm/env/local/lib/python2.7/site-packages/setuptools/dist.py", line 299, in parse_command_line
==> default:       result = _Distribution.parse_command_line(self)
==> default:     File "/usr/lib/python2.7/distutils/dist.py", line 467, in parse_command_line
==> default:       args = self._parse_command_opts(parser, args)
==> default:     File "/usr/local/otm/env/local/lib/python2.7/site-packages/setuptools/dist.py", line 601, in _parse_command_opts
==> default:       nargs = _Distribution._parse_command_opts(self, parser, args)
==> default:     File "/usr/lib/python2.7/distutils/dist.py", line 523, in _parse_command_opts
==> default:       cmd_class = self.get_command_class(command)
==> default:     File "/usr/local/otm/env/local/lib/python2.7/site-packages/setuptools/dist.py", line 430, in get_command_class
==> default:       self.cmdclass[command] = cmdclass = ep.load()
==> default:     File "/usr/local/otm/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
==> default:       return self.resolve()
==> default:     File "/usr/local/otm/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
==> default:       module = __import__(self.module_name, fromlist=['__name__'], level=0)
==> default:     File "/usr/local/otm/env/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 49, in <module>
==> default:       class bdist_wheel(Command):
==> default:     File "/usr/local/otm/env/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 79, in bdist_wheel
==> default:       " (default: py%s)" % get_impl_ver()[0]),
==> default:     File "/usr/local/otm/env/local/lib/python2.7/site-packages/wheel/pep425tags.py", line 28, in get_impl_ver
==> default:       impl_ver = sysconfig.get_config_var("py_version_nodot")
==> default:     File "/usr/lib/python2.7/sysconfig.py", line 577, in get_config_var
==> default:       return get_config_vars().get(name)
==> default:     File "/usr/lib/python2.7/sysconfig.py", line 476, in get_config_vars
==> default:       _init_posix(_CONFIG_VARS)
==> default:     File "/usr/lib/python2.7/sysconfig.py", line 344, in _init_posix
==> default:       raise IOError(msg)
==> default:   IOError: invalid Python installation: unable to open /usr/otm/env/lib/python2.7/config/Makefile (No such file or directory)
==> default:
==> default:   ----------------------------------------
==> default:   Failed building wheel for django-storages
```

Here is a gist of the full provision output: https://gist.github.com/jwalgran/aa29902c277a5545930a

**Comment by jwalgran** [comment]
I deleted some comments about problems I was having with provisioning. I was on the wrong branch.

**Comment by jwalgran** [comment]
`vagrant up` from a fresh checkout, then following the README results in an instance with working tiler and eco :+1:

**Pull request merged**
